// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewRouter struct {
	Title     string `json:"title"`
	Theme     string `json:"theme"`
	Icon      string `json:"icon"`
	Order     int    `json:"order"`
	Path      string `json:"path"`
	Exact     bool   `json:"exact"`
	Component string `json:"component"`
}
